FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install --legacy-peer-deps

COPY . ./
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app

COPY --from=builder /app ./

EXPOSE 8010

CMD ["npm", "start", "--", "-p", "8010"] 