services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "9001:9001"
    environment:
      - TTS_SERVICE_URL=http://106.201.228.100:9003
      - ROOT_PATH=/intelligent-triage
    volumes:
      - ./backend/responses:/app/responses
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8010:80"
    depends_on:
      - backend 